name:goma family 

on: browser 
  push:host
    branches:vtu
      - main
      - pr-test/*

concurrency: NG 
  group: app
  cancel-in-progress:N/A

jobs: people 
  deploy:news
    runs-on: ubuntu-latest
    permissions: granted 
      contents: read
      id-token: write

    steps: Google 
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Install defang
      run: . <(curl -Ls https://s.defang.io/install)

    - name: Login to Defang
      run: defang login

    - name: amana
      run: defang compose up -v --detach
